name: 'GitHub Action for Yarn'
description: 'Wraps the yarn CLI to enable common yarn commands (Now with git access for bower :tada:)'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  cmd:
    description: 'Yarn command'
    required: true
  auth-token:
    description: 'NPM_AUTH_TOKEN'
  registry-url:
    description: 'NPM_REGISTRY_URL'
  git-oauth-key:
    description: 'The git oauth key'
  git-user:
    description: 'github user'
  git-repo:
    description: 'github repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
  env:
    NPM_AUTH_TOKEN: ${{ inputs.auth-token }}
    NPM_REGISTRY_URL: ${{ inputs.registry-url }}
    GIT_OAUTH_KEY: ${{ inputs.git-oauth-key }}
    GIT_USER: ${{ inputs.git-user }}
    GIT_REPO: ${{ inputs.git-repo }}
